server:
  port: 8010
spring:
  application:
    name: zzy-server-user
  datasource:
    url: jdbc:mysql://192.168.189.100:3306/zzy_dev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: mysql
  redis:
    host: 192.168.189.100      #redis地址
    port: 6379
  cloud:
    nacos:
      server-addr: 192.168.189.100:8848  #nacos中心地址，写在和discovery cofig同级，表示他们统一使用该地址
      discovery:
        namespace: 521c58c3-dc43-4338-a6b6-fd0127a4fbc2 #命名空间
#      config:
#        namespace: 521c58c3-dc43-4338-a6b6-fd0127a4fbc2
#        data-id: zzy-server-user.yaml  #指定从 Nacos 中读取的配置文件名
#        file-extension: yaml #配置文件格式
#        refreshable: true  # 可选，配置是否支持动态刷新
#        shared-configs: # 公共配置列表
#          - dataId: redis-dev.yaml # redis公共配置
#            refresh: true           # 是否支持动态刷新
  profiles:
    active: dev

#阿里云短信服务变量配置
aliyun:
  accessKey:
    id:        #accessKey(必填)
    secret:    #秘钥(必填)
  dysms:
    endpoint: dysmsapi.aliyuncs.com #短信服务端点
    sign: 阿里云短信测试 #短信签名
    templateCode: SMS_154950909  #短信模板 Code
#jwt变量配置
jwt:
  expireTime: "#{1000 * 60 * 60 * 24}" # 使用 Spring 表达式计算 时间：24小时
  secretkey: 123456 #jwt加密秘钥
#logging:
#  level:
#    root: debug
